language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: h9T+FXGUEHpDuaYk4GKWSTbAYGeYi6vlO1L44c66u+XqpbjuAWWhXQue26BBNm5UZNR6DCVU0LGT3K7cyi300AmOsl5ainf/l5EJrRJj2izLGKPKNzHTx24lyFFb7c+ljqfT5GbCwoPM8KXgxvnp7zTYsOtFU8WA6vhF2YnLoVoQkYurpRMxxHP+jeyo6x0jVd31YThjbRKgj4xE8GZDnAiPO6H5pAxHhkAp7bWZoA/hLBW8EplHpRwSLuNA3c9iQ1KLhVNiMWr7m1ihm9GTkWCFIMwiz4zVlHBCObBjb3AXc8kOKo3XRLxflsbh7nvF2n6pwR2Xh2cJHNu/yOr1wicAt2lhvnVXHvGIRKTqwlhO3NhJ6pv4mwFovui99tqoV+mWJXC7owq5iMlCN08VozaL+Z4L1tBBRd0R+1AgVLsoJlYrf6qoggFxqbyBhcyb0YbnOyi0KRBQEGqOs0T+wabbaRgfIwaEZGZMdl8sLZgQ2PHaMaGH6p7WdYpkW0yRj1U3VoKugib3+zzirt/mPR4JHPHCZbzUsEF/9VT24pYOedMg3naGGp4FI2Flo1HpomFf17RY/R7uMJRH7E0jAtnuurPM2c+WzF23JiZcZ+GSH8r+s40ZH5LYDnkhhFFV9yxBHy5H/ix8lt3NArPmAhPeYhZ4HP9IeTXlP7wYrJM=
  app: movie-viewing-party
  on:
    repo: RyanDBarnett/viewing_party
    branch: main
  cleanup: 'true'
