language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: oOeb8zwtuV5m+CQhJKcHQpPO48ShXUtOnpBBvIykLVjqxj+tDpiuvuQpL6lk/9s98CVEmRuu+aTLTIA264jsxQpE7HSPTisYnszLDfAtszZVXZByANzdaurD9x9vnp5ujUFN1VcUpTwItv+0+ZUzPvZDpt4uDn6DycPxfGxliV1LbLmjJ9ByGkBVqoW+CM/b4EZSoArKTckSyZC6XLtkrNTQRuQLIU20VSQW6pAAk6r0QY5ENaX6JoFvDZ7Elsgd9ci5WmQYrWAGZ8SSfgObBCCFmVvxJthnQOUGpYOA+glz4tbuO+O+KmPmsDntiEnUtqRLHZIYUMCIPY6ybUGQRlT8chbZNiaHYIHAzTSbUPOaxTT0HUsuFVfnI5Upv3V5pQIlwZSdl8Yk9nm8FfBH4Nkl8Ee/9S5YC6dBbyTUYNNbDMb8tXiLmz9CBx6Tia0Dtm+7jgAUQrn2QO58jXOdEpdq7qOSpYNtUUSuFl7fPixzIVPnMXA2QCo0h4eZu3IvXdGQ2eeIIUQB3AJrhylII+5wcV8fNcm2kgSeqJypINscJF2PM9KjzsUH5kyg9S48F48udrE7f72JZQkp4IWKQYjyXXPzJn0GinSNJlydjxMgSAdpuBomyunVqM60301ev2gA+JoKBsXy6xB414j1fMeGb/oJDhz42uz17FUPQyk=
  app: movie-viewing-party
  on:
    repo: RyanDBarnett/viewing_party
    branch: main
  cleanup: 'false'
  run: rails db:migrate
